// Action Types
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_BY_AMOUNT = 'INCREMENT_BY_AMOUNT';
export const SET_CURRENT_LEAGUE = 'SET_CURRENT_LEAGUE'
export const SET_CALENDAR_DATE = 'SET_CALENDAR_DATE'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SIGN_UP_FOR_WAITLIST = 'SIGN_UP_FOR_WAITLIST'
export const WAITLIST_SIGN_UP_SUCCESS = 'WAITLIST_SIGN_UP_SUCCESS'
export const WAITLIST_SIGN_UP_FAILED = 'WAITLIST_SIGN_UP_FAILED'
export const WAITLIST_SIGN_UP_DEFAULT = 'WAITLIST_SIGN_UP_DEFAULT'
export const WAITLIST_SIGN_UP_FAILED_RESET = 'WAITLIST_SIGN_UP_FAILED_RESET'

export const HELP_CENTER_CONTACT_SUPPORT_SUCCESS = 'HELP_CENTER_CONTACT_SUPPORT_SUCCESS'
export const HELP_CENTER_CONTACT_SUPPORT_FAILURE = 'HELP_CENTER_CONTACT_SUPPORT_FAILURE'
export const HELP_CENTER_CONTACT_SUPPORT_DEFAULT = 'HELP_CENTER_CONTACT_SUPPORT_DEFAULT'
export const HELP_CENTER_CONTACT_SUPPORT_RESET_FAILURE = 'HELP_CENTER_CONTACT_SUPPORT_RESET_FAILURE'

